### ISSUE TITLE
Gain more vertical space

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#10]
We could scroll the media buttons and Visual/Text tabs off the screen when scrolling down, and we could even scroll the bottom status bar off the screen when scrolling up. We could slide both of them up/down while typing, to maximize space. There is precedent for this in a lot of iOS apps. Instapaper, for instance.

**Comment by markjaquith** [comment]
Could also hide the status bar whenever there is no mouse movement.

Something like this would be swell. On scrolling up, the tabs and media button would be shown.

![screen shot 2014-10-04 at 4 34 17 pm](https://cloud.githubusercontent.com/assets/353790/4516737/fa6c3bda-4c05-11e4-9928-9bcf40f80010.png)

**Comment by ellatrix** [comment]
Sounds good. Then the media button and tabs don't pin when scrolling down, but slide down early when scrolling up?
We could also slide away when you start typing and slide back on scroll/mouse movement. So no hiding on scroll.

**Comment by ellatrix** [comment]
I'd hide the element path completely. Not many people use it (I think), and we can show it on ALT+F11. Then hide it again on the next nodechange event.

**Comment by ellatrix** [comment]
Let's discuss this issue in depth next Monday. Not sure what the best solution is and whether we should actually do this.

**Comment by michaelbeil** [comment]
Do we think any users may freak out when the status bar and media buttons fade away? I personally want this. And when is the IRC on Monday?

**Comment by ellatrix** [comment]
It's 20:00 UTC. :)

**Comment by ellatrix** [comment]
I think we agreed on keeping them visible, as we're now fading them. #21.
