### ISSUE TITLE
Fade out the toolbar

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#11]
We could fade out the toolbar a bit. Dim the lights, as it were.

![screen shot 2014-10-04 at 4 43 08 pm](https://cloud.githubusercontent.com/assets/353790/4516752/1d7a6e0c-4c07-11e4-9fef-98003c0c45a1.png)

**Comment by ellatrix** [comment]
For this we'll need to add another overlay (for touch devices), so it can fade in, either by itself or together with the rest of the UI.
What would be best? Fade everything back in when you hover the admin bar, or fade in the admin bar separately? And what about hiding it entirely?

**Comment by markjaquith** [comment]
Looks like we got these questions resolved. Working quite nicely.
