### ISSUE TITLE
Main column meta boxes shouldn't fade out

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#12]
I think these should always be faded in. Otherwise when you hit the bottom and keep scrolling it makes a weird blank area under the editor that there is no context for.

**Comment by michaelbeil** [comment]
agreed. gonna download latest and check more.

**Comment by helen** [comment]
Might work to have everything fade back in once you get to that point.

**Comment by ellatrix** [comment]
Everything fades back in at that point, if you scroll down and the mouse goes over the editor area border. I'm not too bothered that there's nothing under it. Just move a bit further, or move the mouse over it and it fades in. :)

**Comment by markjaquith** [comment]
This just looks and feels weird to me.

![screen shot 2014-10-13 at 6 59 39 pm](https://cloud.githubusercontent.com/assets/353790/4621536/a71df1de-532c-11e4-8d08-930b02cfdb5d.png)

Why is there all that space there? Because there are things there. But I can't see them, so it doesn't click for me until I happen to move my mouse down.

**Comment by michaelbeil** [comment]
Now that the content editor is slightly larger when a user enters focus mode this seems to be better than before, however, the gaping space below the editor where post meta sits, is a little strange.

**Comment by ellatrix** [comment]
Okay, so how do we solve this? I don't really mind that there is space at the bottom. Atm it will fade in depending on where the mouse is. If the mouse is still in the editor it won't fade back in. The alternative is to fade in as soon as the editor is scrolled up x pixels form the bottom.

I know @gcorne had some thoughts on this. He proposed not fading in at all on scroll, but fade in immediately after when the mouse moves (away from the editor).

**Comment by markjaquith** [comment]
I think we let it stay as-is for now.

**Comment by gcorne** [comment]
> I know @gcorne had some thoughts on this. He proposed not fading in at all on scroll, but fade in immediately after when the mouse moves (away from the editor).

Yeah, I was concerned about the sensation when the editor is blurred when scrolling. I think it needs to be clear to the user what actions trigger the focusing and blurring of the editor. If it isn't clear, the focus experience is jarring. When scrolling to the point where the mouse leaves the editor, it is not clear to the user why the editor is being blurred because we don't think of scrolling as moving the mouse. My idea was to only blur when scrolling if the mouse is moved a certain distance after the last scroll event.

**Comment by ellatrix** [comment]
Okay, I think we should fade in when the editor is less than 1/3 or so regardless of the mouse position. If the mouse is out and moves away (10px) fade in too.

**Comment by ellatrix** [comment]
Any issues around DFW should be reported through [Trac](https://core.trac.wordpress.org/newticket) now.
