### ISSUE TITLE
Add toggle so this feature can be disabled per-user

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#13]
This feature is very opinionated. Users might want to disable it. Thankfully, we can do this without any (or much) new UI, as the DFW (full screen) button was already in place. We can use this as a toggle between auto-DFW (which should be default), and no-DFW.

**Comment by ellatrix** [comment]
What icon should we use? The current one wouldn't make much sense.

**Comment by markjaquith** [comment]
@melchoyce thoughts?

**Comment by ellatrix** [comment]
The only icon that it somewhat relevant is this: https://github.com/melchoyce/dashicons/blob/master/svg/smiley.svg

:D

**Comment by melchoyce** [comment]
Would we be getting rid of DFW entirely if this merges? If so, I'd just reuse that button.

**Comment by ellatrix** [comment]
Yes, but the icon for that button is not good. We're not toggling fullscreen.

**Comment by melchoyce** [comment]
But it _feels_ fullscreen, right? Do you think users will care about the difference?

**Comment by markjaquith** [comment]
Original DFW wasn't really fullscreen either. I'm not sure the distinction matters.

What could we use to indicate toggle state? Make it look dim and inactive when auto DFW is disabled?

**Comment by ellatrix** [comment]
Okay, let's use the fullscreen icon then.
Just use the active buttons styles?

**Comment by ellatrix** [comment]
Like bold etc.

**Comment by melchoyce** [comment]
Yeah, I'd just use what's already there.

**Comment by michaelbeil** [comment]
No smiley? sad day. just tested the dfw/focus toggle, and it doesn't do anything yet.

**Comment by ellatrix** [comment]
What does it not do? If you toggle it off, does the fading not stop?

**Comment by michaelbeil** [comment]
It doesn't stop. Focus mode remains on. http://beil.io/1guSD

**Comment by ellatrix** [comment]
Any JS errors? Are you sure you pulled the latest changes?

**Comment by michaelbeil** [comment]
No JS errors. And I believe so. I pull again.

**Comment by ellatrix** [comment]
Did it work?

**Comment by michaelbeil** [comment]
Not quite yet @avryl. will check again tomorrow via other browsers.
