### ISSUE TITLE
Stop #edit-slug-box from dancing

### ISSUE THREAD

**Issue by ocean90** [ellatrix/focus#14]
See https://cloudup.com/cN4A3bX-5qJ
There should be a small delay when hovering #edit-slug-box, something like hoverIntent does.

**Comment by ellatrix** [comment]
Yeah, was thinking the same. :) Thanks for testing!

**Comment by ellatrix** [comment]
Is it better? Added stop() in 11c6edcc57d9dbba06cc911ea186c0cd5ffebb22.

**Comment by michaelbeil** [comment]
looks much better: http://beil.io/zaOS

**Comment by ocean90** [comment]
Much better! :+1:
