### ISSUE TITLE
Admin Bar icons "disappear" when returning from focus

### ISSUE THREAD

**Issue by kraftbj** [ellatrix/focus#15]
When Focus/new DFW is enabled, the admin bar fades, but when returning to "full of distraction" mode, the admin bar items are hidden from view.

If hovering, they reappear (one-by-one) or choosing Inspect Element causes them all to reappear, so didn't pin it down beyond the screenshot.

![screen shot 2014-10-08 at 16 07 00](https://cloud.githubusercontent.com/assets/88897/4567235/4b9376c8-4f2f-11e4-849d-5180863d2c29.png)

**Comment by ellatrix** [comment]
Hm. How do I reproduce this?

**Comment by michaelbeil** [comment]
Haven't been able to reproduce this.

**Comment by markjaquith** [comment]
@kraftbj What browser? Can you still reproduce this?

**Comment by ellatrix** [comment]
Probably fixed somewhere.
