### ISSUE TITLE
Editor footer toolbar moves off-screen

### ISSUE THREAD

**Issue by johnbillion** [ellatrix/focus#16]
In 4.0 the footer toolbar in the editor (with the word count etc) sticks to the bottom of the screen.

With Focus active, it attaches to the scroll position and moves off the bottom of the screen.

**Comment by ellatrix** [comment]
We decided to unpin the the word count etc. if the kitchensink is toggled off. If you want "advanced" tools, you can turn it on and it will pin, plus show the element path. The element path is hidden by default.
