### ISSUE TITLE
Keep status bar at bottom of screen (visible) when typing at bottom

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#17]
Relates to #16

I think that when you are typing at the bottom, the status bar should be visible. Right at the bottom of the screen (or maybe with a small amount of spacing from the bottom).

Doing so will give you a sense of place. Confidence that you are at the bottom.

![screen shot 2014-10-13 at 6 46 56 pm](https://cloud.githubusercontent.com/assets/353790/4621414/e2576548-532a-11e4-8bdd-09f4eb6f59c6.png)

**Comment by ellatrix** [comment]
Same here, let's fix #18 first.
