### ISSUE TITLE
Consistent amount of padding at bottom when typing at bottom

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#18]
When you're typing at the bottom, there should be a consistent amount of space between the last line and the bottom of the editor. Right now it’s pretty good when in non-kitchen-sink mode. But when the kitchen sink is open and the double-height bottom status bar (with path) is visible, there is very little padding, and it feels cramped.

**Comment by ellatrix** [comment]
First we need to fix this: https://core.trac.wordpress.org/ticket/29954.
So looking at that now. :)
