### ISSUE TITLE
Longer fade-out/dim delay when tabbing into title/editor from outside title/editor

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#19]
People who use the keyboard to navigate might tab _through_ the title/editor on their way to someplace else. We should have a longer delay here, so that they don't get a distracting fade/dim/unfade/undim as they pass through, quickly.

I was thinking 2 seconds to start, and see how that feels. If they linger focus for that long, they're probably not tabbing through.

**Comment by ellatrix** [comment]
I think 1 second is enough. :)
