### ISSUE TITLE
Re-enter focus mode if mouse leaves, then returns, with editor/title focus

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#20]
Right now if you mouse out of the editor area, you leave focus mode. And you don't go back into focus mode until you enter a keystroke in editor area, or if you again click into the editor area. I find myself leaving focus mode unintentionally a lot. Say, when scrolling to the bottom of the post and accidentally mousing over the meta boxes below the editor. When I correct my mouse position, the focus mode doesn't return, and I get confused, and click randomly into the editor, losing my caret position. I think we should re-enter focus mode if the mouse returns and focus hasn't left.

**Comment by markjaquith** [comment]
There are probably some instances in which we do NOT want to do this. For instance, if they mouseover anything in the menu or the site toolbar, consider focus "lost". Because the menus fly out over the editor, so if they "miss" a menu, they will find themselves over the editor, which would make the menu go away. That would be frustrating.

Could also have a general "grace period". If the mouse leaves for a long enough time, perhaps consider focus to be lost.

**Comment by markjaquith** [comment]
The menu issue wasn't addressed, and it is, as I suspected, annoying.

Also think that it should be a grace period, not indefinite. Proposed:
1. You have 4 seconds to return the hover.
2. Hovering toolbar or side menu instantly ends the grace period.

**Comment by ellatrix** [comment]
Ah, ah thought you meant that if they'd hover over a fly out submenu it would fade out, which isn't the case. But yes, if they accidentally move next to it, it triggers the fade out.

**Comment by ellatrix** [comment]
Forgot to tag a11f73b3989987300e925282e4abdbc75c1caf60 with this ticket.

Thinking about how this would work for the admin bar...

**Comment by markjaquith** [comment]
Same? Hover kills the grace period?

**Comment by ellatrix** [comment]
Yeah, but right now you can hover the admin bar without leaving focus mode. Maybe that should be removed so it behaves like the rest.

**Comment by ellatrix** [comment]
Not _that_ useful anyway.

**Comment by michaelbeil** [comment]
the behavior is better. do we think having a hover over the admin bar should kill the grace period, thus leaving focus mode? or leave the admin bar as is?

**Comment by markjaquith** [comment]
Eh, I think it’s okay. The reason the menu was so annoying was because it completely disappears. The admin toolbar doesn't go away.
