### ISSUE TITLE
Dim the media/editor/mode controls when actively typing

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#21]
Right now the media button and the editor controls and the mode (visual/text) controls are the most "visible" elements when you're composing a post. Even when you're just typing away. I don't think they need to be this "in your face" all the time. Can we dim them like we dim the site toolbar when the user is just typing, but bring them back upon ANY mouse movement, or on any text selection (which could indicate they want to link/bold/whatever something)? I would love to just be able to type type type without all those buttons staring at me so brightly.

**Comment by ellatrix** [comment]
Haha, how dare they be in my face all the time.

I'll come back to this tomorrow. It works nicely but we'll have to use a separate overlay for each of those areas to make it visually okay. There's a line between the tabs and toolbar. :/

https://cloudup.com/cPv4qhfqkTF

**Comment by ellatrix** [comment]
It looks like any kind of scroll (programmatic/manual) triggers a mousemove event, at least on a mac. So if you're typing and the editor scroll with the text, the toolbars fade in an out...

**Comment by ellatrix** [comment]
Hm, and simply caching the pageX|Y or clientX|Y from the event won't work inside the editor since the whole iframe moves (and technically all the coordinate change, though not relative to the main window). We could use look at the position of the iframe, but that's way too expensive for a mousemove event.

**Comment by ellatrix** [comment]
Reopened because this might cause a bit too much movement.

**Comment by markjaquith** [comment]
We rolled this back. I retract my brightness complaints.
