### ISSUE TITLE
Clicking into the margins of the editor doesn't give a visible caret

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#22]
As we are centering content, there are now margins. If you click a margin, you go into focus mode, but you don't get a visible caret. You _can_ start typing and it will work, but it is confusing that there is no caret, and people might doubt the editor is focused.

**Comment by markjaquith** [comment]
Seems to happen more when there is no or very little content.

**Comment by ellatrix** [comment]
That seems to fix it for me. Reopen if it's still buggy. :)
