### ISSUE TITLE
When writing the text in the main text area's left and top margins seem too big

### ISSUE THREAD

**Issue by chaselivingston** [ellatrix/focus#25]
You can see the behavior in https://cloudup.com/cm5d1JUOY0o on Twenty Fifteen, also happening with Twenty Fourteen on WP 4.1.

**Comment by michaelbeil** [comment]
is this behavior still happening @chaselivingston?

**Comment by chaselivingston** [comment]
@michaelbeil Yes, still happening as of 0.2.1.

**Comment by michaelbeil** [comment]
I am experiencing it as well on trunk with twenty fourteen and twenty fifteen @chaselivingston.  

@avryl and @markjaquith, when focus is activated, content cannot be added to the editor when on 4.1 alpha.

**Comment by markjaquith** [comment]
> when focus is activated, content cannot be added to the editor when on 4.1 alpha.

@michaelbeil please open new issues for new issues. :smirk_cat:

**Comment by michaelbeil** [comment]
you can't make me. ok, fine. done. sorry about that.

**Comment by ellatrix** [comment]
Any issues around DFW should be reported through [Trac](https://core.trac.wordpress.org/newticket) now.
