### ISSUE TITLE
Sometimes exiting a modal triggers a fade in

### ISSUE THREAD

**Issue by ellatrix** [ellatrix/focus#26]
This is probably because the user moved the mouse a tiny bit away from the editor.
See user test 2: https://wptestervids.files.wordpress.com/2014/10/52b2a9a6.mp4

We could "require" x pixels moving away from the editor beforr triggering a fade in.

**Comment by michaelbeil** [comment]
after several tests i experienced this fade in only when i moved my mouse into the post settings area, not when i moved my cursor back into the editor.
