### ISSUE TITLE
Only do the initial fadeOut on keyup with focus

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#28]
Was talking with @MichaelArestad and have become convinced that we are fading out too readily, in ways that are distracting.

I propose that we restrict the initial fade out to keyup within TinyMCE. So, basically, remove the "click" and "focus" ones on the MCE body, and remove the title actions.

This means fewer unintentional fade outs for transient focus or quick edits. But when the user is actually composing something (by typing), they get the distraction free mode.

**Comment by michaelbeil** [comment]
I was just going to suggest something like this as "focus" would engage within a title action and then stay more delayed within the body. Pulling down the latest from dev branch.
