### ISSUE TITLE
black admin bar in focus

### ISSUE THREAD

**Issue by michaelbeil** [ellatrix/focus#31]
just wondering if the admin bar will remain when a user enters focus mode.

![admin bar in focus](https://cloud.githubusercontent.com/assets/4752949/4889131/38d0f344-6393-11e4-95dd-3c28bcb96dfb.png)

**Comment by ellatrix** [comment]
We had some discussion about this earlier and we don't want to hide it because
1) the toolbar is always visible on the back-end and front-end, and
2) hiding would mean we have to slide up the editor toolbar too when the editor is scrolled down, which complicates things a lot (unless we leave it 32px form the top).

**Comment by michaelbeil** [comment]
1) i feel you on this. i haven't checked, but will the toolbar be filterable?
2) i think leaving the editor toolbar visible is good and wasn't really vouching for that to be hidden.

**Comment by ellatrix** [comment]
What do you mean with filterable?

**Comment by michaelbeil** [comment]
let's say a theme wants to take advantage of focus mode (DFW), could the black toolbar be changed to white or orange from the user's view, or completely removed in a custom wp admin? i know DFW will be off by default, just was curious of potential ways to customize DFW with a unique UI. 

could be neat to see different use cases come up for DFW.

does this make sense? or am i just completely in left field?

**Comment by ellatrix** [comment]
Fading to black was actually a mistake, it should fade to 30%. Fixed now. :)
Did you have any other concerns?

**Comment by michaelbeil** [comment]
oh ok. that could be nice. no other concerns right now.
