### ISSUE TITLE
Should the sidebar widgets also slide away?

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#5]
Right now the menu slides away to the left, and the sidebar widgets fade out. Should they both do the same thing? I like the sliding, because it is an established UI paradigm (think an auto-hiding dock or fullscreen bar in OS X), and it suggests that the "stuff" is still there, just tucked off-screen.

**Comment by markjaquith** [comment]
Also, the "Screen Options" and "Help" tabs could slide up.

**Comment by ellatrix** [comment]
I really like it too. Wasn't sure what others would think about it. :)
Makes the overlay approach more difficult to implement though. But everything is possible. We could add an overlay just for the faded elements so we can detect a touch.

**Comment by markjaquith** [comment]
Could we slide/fade, then replace them in an opacity=0 state? Then they can act as a hover target. On hover, move into "slid out" state, then slide back and fade in? Dunno if that's more complicated than just doing an overlay.

**Comment by ellatrix** [comment]
The way it's now, we don't need the element to detect hovering. Theoretically we could detect a touch outside then editor area and preventDefault(). I wish I had a touch device.
OR don't use the overlay for fading but just to detect the touch. There's a few roads we could take.

**Comment by pbearne** [comment]
I can see the case for sliding the menu to the icon version when we go DFW and fading them is nice I am not so sure that sliding the meta box works as well if we do slide them we need icons for each metabox so there is a hove target for each box. 

As I type I can see in my head a stack of icons for meta boxes including the boxes below the editor all stacked up on the left and them flying out on hove over the DFW editor this might work and solve the problem content below the fold

**Comment by markjaquith** [comment]
> if we do slide them we need icons for each metabox so there is a hove target for each box.

What? I just meant sliding them off the screen, just like how the menu slides off the screen. Some motion, instead of a straight fade to opacity=0.

**Comment by azaozz** [comment]
What about the "double fading", first to 0.2-0.3, then after several seconds to 0? That would make it very reassuring for the users: "the UI is still there, just move the mouse/touch it".

Also not sure how the bottom postboxes would work with sliding. Or are they still going to fade?

**Comment by ellatrix** [comment]
@azaozz Instead of the sliding, or together and just for the faded elements (i.e. slide and fade a bit, then fully).

**Comment by azaozz** [comment]
Yeah, we could try a combination of sliding and fading:
1. Fade to 0.2.
2. Slide out after 5-10 sec.

Still not sure about the "under the editor" stuff.

**Comment by pbearne** [comment]
@azaozz thats what I liked about collapsing the meta boxes to icons  on the left as we can add the "under the editor" stuff. into the column and just flow them (like menu) on a hover 

Easy to to get to no scrolling  and balances the menu

**Comment by pbearne** [comment]
@markjaquith sorry I know this is a new idea it just came to be and is feature creep but I do believe it solves the problem

let me create a image for this

**Comment by azaozz** [comment]
@pbearne the problem is that there can be quite a few other elements on that screen. In addition to the postboxes, there are several actions fired at various places: at the top, after the title and the editor, before/after metaboxes areas, at the bottom. Plugins can add arbitrary elements there.

**Comment by pbearne** [comment]
![icons](https://cloud.githubusercontent.com/assets/46270/4511632/fac90100-4b36-11e4-953c-b3d3e1c54979.png)

Here is very quick mock (I use the menu icons) and am show 2  meta boxes in the hover (or toggle) state

**Comment by pbearne** [comment]
@azaozz the other elements will have to be handled no matter how we do this 
In the current DFW they are gone any way so adding the meta boxes in an icon bar would increase the actions available in DFW

I am just putting this idea out if it doesn't fly thats OK

**Comment by azaozz** [comment]
Right :) In DFW the UI is hidden behind an overlay, then the editor and title are pulled on top of that overlay. This ensures we hide everything. If we move away from sliding, we can fade-out (fast) and then hide that overlay revealing the rest of the UI all at the same time.

Similar to opening and closing DFW but with better timing and on hover/touch, etc.

**Comment by michaelbeil** [comment]
i like the slide and fade approach. @azaozz makes a good point on the fast fade-out to hide the overlay so the UI is viewable upon hover.

**Comment by ellatrix** [comment]
So I tried the mouseenter approach to fade back in instead of detecting when the mouse goes outside the editor area. It works if we put the menu back in it's original place with opacity 0 as Mark suggested. This saves us a lot of code as we don't have to recalculate the editor area all the time.

However, I've been playing with a touchscreen :-), and it looks like using an overlay div is unavoidable. You can cancel the touch events on the faded elements (so that you don't accidentally publish a post), but you can't cancel the events already bound to all the child elements... This means that if you happen to touch a meta box title, it collapses. If you touch a menu item with a submenu, it flies open. Since plugins can add anything to the screen, there's no way to make sure all events are canceled or unbound.

So I'll continue experiment with a with an overlay. Instead of calculating the editor area, we could try to manipulate the editor container with CSS so it has a 20px buffer and then fade in on mouseleave. Anything is better than having to recalculate it are all the time.

**Comment by ellatrix** [comment]
Overlay and CSS buffer work well. Now, should the post meta boxes on the side fade or slide?

**Comment by markjaquith** [comment]
I think we've decided to not introduce any more motion.
