### ISSUE TITLE
Can the post content block be centered within the editor?

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#6]
Not center-aligned, just the width-restricted block itself, centered:

![screen shot 2014-10-03 at 2 03 58 pm](https://cloud.githubusercontent.com/assets/353790/4510162/bdc778cc-4b27-11e4-9d87-0a0af8bed381.png)

We talked about this in our planning session and I think it's something we can consider again.

**Comment by pbearne** [comment]
if we do this can we add an option for the theme authors to set the width

This would help the user to see how the content layout looks 

this comment is not just for if it centered

**Comment by ellatrix** [comment]
@pbearne They already can?

**Comment by pbearne** [comment]
@avryl 
Thanks found it 
set_user_setting( 'dfw_width', 1000 );

**Comment by ellatrix** [comment]
Not working on iOS. Needs to be checked in other (mobile) browsers.
