### ISSUE TITLE
Disable on touch screen with keyboard?

### ISSUE THREAD

**Issue by ellatrix** [ellatrix/focus#8]
Probably best to disable the fading on small screen devices. There's not much benefit. We could improve things with Focus in other ways though. Since the keyboard rearranges the UI anyway and doesn't leave much space for the editor, we could switch to a fullscreen editor and change it back when the keyboard hides. In an other plugin I'd line experiment with an inline toolbar, but this could be the start of a better writing experience on mobile devices.

**Comment by michaelbeil** [comment]
good thoughts @avryl. i agree with this decision.

**Comment by markjaquith** [comment]
All sorted?
