### ISSUE TITLE
Lock "focus mode" when media modal is open

### ISSUE THREAD

**Issue by markjaquith** [ellatrix/focus#9]
@ryanboren notes that when you have the media modal open, any mouse movement will cause the "focus mode" under the modal to go away. We should lock focus mode while the media modal is open.

**Comment by ellatrix** [comment]
Yeah, I know. I'm trying to solve it for all modals...

**Comment by ellatrix** [comment]
With the overlay though, it won't fade back in as long as the modal is open. But as soon as you close it, the mouse ends up next to the editor, so it the fade in is triggered. Note sure how to solve. We could require a hover over the editor after the modal closes before fading back in. Or a timer. But both could be annoying.

**Comment by ellatrix** [comment]
Actually we could make it a bit smarter. On hovering the overlay we could detect whether the mouse starts moving from outside the editor. If that's the case, then we know a modal was open previously. Then we can prevent a fade in if we see that the mouse moves towards the editor. As soon as it moves in the opposite direction, we fade in.

**Comment by ellatrix** [comment]
Fixed in 60b744362c153820d80328fb703e03de140df2fe.
